Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'rspec-html.gemspec'

Gemspec/RequiredRubyVersion:
  Enabled: false

AllCops:
  NewCops: enable

# Compatibility with older (< 2.6) Rubies.
Style/SlicingWithRange:
  Enabled: false
