require:
  - 'rubocop-rake'
  - 'rubocop-rspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'rspec-html.gemspec'

AllCops:
  NewCops: enable

# Compatibility with older (< 2.6) Rubies.
Style/SlicingWithRange:
  Enabled: false
